steps:
  - name: 'gcr.io/distroless/java17-debian11:debug'
    entrypoint: '/busybox/sh'
    args:
      - -c
      - |
        ln -s /busybox/sh /bin/sh
        ln -s /busybox/env /usr/bin/env
        chmod +x /workspace/gradlew
        /workspace/gradlew --console=plain --no-daemon --gradle-user-home=/home/.gradle jib -PprojectDataImageTargetEnv=prod
  - name : 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hospital-main-api-server-prod'
      - '--image=asia-northeast3-docker.pkg.dev/hospital-440202/hospital/prod:latest'
      - '--platform=managed'
      - '--region=asia-northeast3'
options:
  logging: CLOUD_LOGGING_ONLY