spring:
  config:
    activate:
      on-profile: prod


  application:
    name: emergency_backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mvc:
    contentnegotiation:
      favor-parameter: false
      favor-path-extension: false
      favor-header: true
      media-types:
        json: application/json
    default-response-type: application/json

server:
  port: 8080



springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: INFO
    daelim:
      emergency_backend: INFO