package daelim.emergency_backend.database

import jakarta.persistence.*
import java.sql.Timestamp
import java.util.Date

@Entity
@Table(name = "emergency_hospital_data")
class EmergencyHospitalData(
    @Id
    @GeneratedValue
    val id: Int = 0,

    @Column val result_code: String? = null,
    @Column val result_msg: String? = null,
    @Column val rnum: String? = null,
    @Column val hpid: String? = null,
    @Column val phpid: String? = null,
    @Column val hvidate: Date? = null,
    @Column val hvec: String? = null,
    @Column val hvoc: String? = null,
    @Column val hvcc: String? = null,
    @Column val hvncc: String? = null,
    @Column val hvccc: String? = null,
    @Column val hvicc: String? = null,
    @Column val hvgc: String? = null,
    @Column val hvdnm: String? = null,
    @Column val hvctayn: String? = null,
    @Column val hvmriayn: String? = null,
    @Column val hvangioayn: String? = null,
    @Column val hvventiayn: String? = null,
    @Column val hvventisoayn: String? = null,
    @Column val hvincuayn: String? = null,
    @Column val hvcrrtayn: String? = null,
    @Column val hvecmoayn: String? = null,
    @Column val hvoxyayn: String? = null,
    @Column val hvhypoayn: String? = null,
    @Column val hvamyn: String? = null,
    @Column val hv1: String? = null,
    @Column val hv2: String? = null,
    @Column val hv3: String? = null,
    @Column val hv4: String? = null,
    @Column val hv5: String? = null,
    @Column val hv6: String? = null,
    @Column val hv7: String? = null,
    @Column val hv8: String? = null,
    @Column val hv9: String? = null,
    @Column val hv10: String? = null,
    @Column val hv11: String? = null,
    @Column val hv12: String? = null,
    @Column val hv13: String? = null,
    @Column val hv14: String? = null,
    @Column val hv15: String? = null,
    @Column val hv16: String? = null,
    @Column val hv17: String? = null,
    @Column val hv18: String? = null,
    @Column val hv19: String? = null,
    @Column val hv21: String? = null,
    @Column val hv22: String? = null,
    @Column val hv23: String? = null,
    @Column val hv24: String? = null,
    @Column val hv25: String? = null,
    @Column val hv26: String? = null,
    @Column val hv27: String? = null,
    @Column val hv28: String? = null,
    @Column val hv29: String? = null,
    @Column val hv30: String? = null,
    @Column val hv31: String? = null,
    @Column val hv32: String? = null,
    @Column val hv33: String? = null,
    @Column val hv34: String? = null,
    @Column val hv35: String? = null,
    @Column val hv36: String? = null,
    @Column val hv37: String? = null,
    @Column val hv38: String? = null,
    @Column val hv39: String? = null,
    @Column val hv40: String? = null,
    @Column val hv41: String? = null,
    @Column val hv42: String? = null,
    @Column val hv43: String? = null,
    @Column val duty_name: String? = null,
    @Column val duty_tel3: String? = null,
    @Column val last_updated: Timestamp? = null,
)