package daelim.emergency_backend.models.AvailavleBedInfo

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement

@JsonIgnoreProperties(ignoreUnknown = true)
@JacksonXmlRootElement(localName = "item")
data class AvailableBedInfos(
    @JacksonXmlProperty(localName="rmum") val rmum:Int, //일련번호
    @JacksonXmlProperty(localName="hpid") val hpid:String, //기관코드
    @JacksonXmlProperty(localName="phpid") val phpid:String, //구 기관코드
    @JacksonXmlProperty(localName="hvidate") val hvidate:String, //입력일시
    @JacksonXmlProperty(localName="hvec") val hvec:Int, //일반병상 수
    @JacksonXmlProperty(localName="hvoc") val hvoc:Int, //수술실 병상 수
    @JacksonXmlProperty(localName="hvcc") val hvcc:Int, //중환자실 신경과 병상 수
    @JacksonXmlProperty(localName="hvncc") val hvncc:Int, //중환자실 신생아 병상 수
    @JacksonXmlProperty(localName="hvccc") val hvccc:Int, //중환자실 흉부외과 병상 수
    @JacksonXmlProperty(localName="hvicc") val hvicc:Int, //중환자실 일반 입원실 수
    @JacksonXmlProperty(localName="hvdnm") val hvdnm:String, //당직의 이름
    @JacksonXmlProperty(localName="hvctayn") val hvctayn:Boolean, //CT 가용 여부
    @JacksonXmlProperty(localName="hvmriayn") val hvmriayn:Boolean, //MRI 가용 여부
    @JacksonXmlProperty(localName="hvangioayn") val hvangioayn:Boolean, //혈관촬영기 가용 여부
    @JacksonXmlProperty(localName="hvventiayn") val hvventiayn:Boolean, //인공호흡기 가용 여부
    @JacksonXmlProperty(localName="hvventisoayn") val hvventisoayn:Boolean, //인큐베이터 가용 여부
    @JacksonXmlProperty(localName="hvcrrtayn") val hvcrrtayn:Boolean, //CRRT 가용 여부
    @JacksonXmlProperty(localName="hvecmoayn") val hvecmoayn:Boolean, //ECMO 가용 여부
    @JacksonXmlProperty(localName="hvoxyayn") val hvoxyayn:Boolean, //고압 산소 치료기 가용 여부
    @JacksonXmlProperty(localName="hvhypoayn") val hvhypoayn:Boolean, //중심 체온 조절 유도기 가용 여부
    @JacksonXmlProperty(localName="hvamyn") val hvamyn:Boolean, //구급차가용여부
    @JacksonXmlProperty(localName="hv1") val hv1:String, //응급실 당직의 직통 연락처
    @JacksonXmlProperty(localName="hv2") val hv2:String, //내과 중환자실 수
    @JacksonXmlProperty(localName="hv3") val hv3:String, //외과 중환자실 수
    @JacksonXmlProperty(localName="hv4") val hv4:String, //외과입원실(정형외과) 수
    @JacksonXmlProperty(localName="hv5") val hv5:String, //신경과입원실 수
    @JacksonXmlProperty(localName="hv6") val hv6:String, //신경외과 중환자실 수
    @JacksonXmlProperty(localName="hv7") val hv7:String, //약물중환자 수
    @JacksonXmlProperty(localName="hv8") val hv8:String, //화상 중환자실 수
    @JacksonXmlProperty(localName="hv9") val hv9:String, //외상 중환자실 수
    @JacksonXmlProperty(localName="hv10") val hv10:Boolean, //소아 가능 여부
    @JacksonXmlProperty(localName="hv11") val hv11:Boolean, //인큐베이터(보육기) 가용 여부@field:Element(name="")
    @JacksonXmlProperty(localName="hv12") val hv12:String, //솓아당직의 직통연락처
    @JacksonXmlProperty(localName="hv13") val hv13:String, //격리진료구역 음압격리병상 수
    @JacksonXmlProperty(localName="hv14") val hv14:String, //격리진료구역 일반격리병상 수
    @JacksonXmlProperty(localName="hv15") val hv15:String, //소아음악격리 수
    @JacksonXmlProperty(localName="hv16") val hv16:String, //소아일반격리 수
    @JacksonXmlProperty(localName="hv17") val hv17:String, //응급전용 중환자실 음압격리 수
    @JacksonXmlProperty(localName="hv18") val hv18:String, //응급전용 중환자실 일반격리 수
    @JacksonXmlProperty(localName="hv19") val hv19:String, //응급전용 입원실 음압격리 수
    @JacksonXmlProperty(localName="hv21") val hv21:String, //응급전용 입원실 일반격리 수
    @JacksonXmlProperty(localName="hv22") val hv22:String, //감염병 전담병상 중환자실 내 음압격리병상 수
    @JacksonXmlProperty(localName="hv23") val hv23:String, //감염병 전담병상 중환사실 수
    @JacksonXmlProperty(localName="hv24") val hv24:String, //감염 중증 병상 수
    @JacksonXmlProperty(localName="hv25") val hv25:String, //감염 준-중증 병상 수
    @JacksonXmlProperty(localName="hv26") val hv26:String, //감염 중등증 병상 수
    @JacksonXmlProperty(localName="hv27") val hv27:String, //코호트 격리 수
    @JacksonXmlProperty(localName="hv28") val hv28:String, //소아 수
    @JacksonXmlProperty(localName="hv29") val hv29:String, //응급실 음압 격리 병상 수
    @JacksonXmlProperty(localName="hv30") val hv30:String, //응급실 일반 격리 병상 수
    @JacksonXmlProperty(localName="hv31") val hv31:String, //응급전용 중환자실 수
    @JacksonXmlProperty(localName="hv32") val hv32:String, //중환자실 소아 수
    @JacksonXmlProperty(localName="hv33") val hv33:String, //응급전용 소아중환자실 수
    @JacksonXmlProperty(localName="hv34") val hv34:String, //중환자실 심장내과 수
    @JacksonXmlProperty(localName="hv35") val hv35:String, //중환자실 음압격리 수
    @JacksonXmlProperty(localName="hv36") val hv36:String, //응급전용 입원실 수
    @JacksonXmlProperty(localName="hv37") val hv37:String, //응급전용 소아입원실 수
    @JacksonXmlProperty(localName="hv38") val hv38:String, //외상전용 입원실 수
    @JacksonXmlProperty(localName="hv39") val hv39:String, //외상전용 수술실 수
    @JacksonXmlProperty(localName="hv40") val hv40:String, //정신과 폐쇄병동 입원실 수
    @JacksonXmlProperty(localName="hv41") val hv41:String, //음압격리 입원실 수
    @JacksonXmlProperty(localName="hv42") val hv42:String, //분만실 수
    @JacksonXmlProperty(localName="hv43") val hv43:String, //화상전용처치실 수
    @JacksonXmlProperty(localName="dutyname") val dutyname:String, //기관명
    @JacksonXmlProperty(localName="dutytel3") val dutytel3:String, //응급실 전화
    @JacksonXmlProperty(localName="HVS01") val HVS01:String, //일반 기준 수
    @JacksonXmlProperty(localName="HVS02") val HVS02:String, //소아 기준 수
    @JacksonXmlProperty(localName="HVS03") val HVS03:String, //응급실 음압 격리 병상 기준 수
    @JacksonXmlProperty(localName="HVS04") val HVS04:String, //응급실 일반 격리 병상 기준 수
    @JacksonXmlProperty(localName="HVS05") val HVS05:String, //응급전용 중환자실 기준 수
    @JacksonXmlProperty(localName="HVS06") val HVS06:String, //중환자실 내과 기준 수
    @JacksonXmlProperty(localName="HVS07") val HVS07:String, //중환자실 외과 기준 수
    @JacksonXmlProperty(localName="HVS08") val HVS08:String, //중환자실 신생아 기준 수
    @JacksonXmlProperty(localName="HVS09") val HVS09:String, //중환자실 소아 기준 수
    @JacksonXmlProperty(localName="HVS10") val HVS10:String, //응급전용 소아중환자실 기준 수
    @JacksonXmlProperty(localName="HVS11") val HVS11:String, //중환자실 신경과 기준 수
    @JacksonXmlProperty(localName="HVS12") val HVS12:String, //중환자실 신경외과 기준 수
    @JacksonXmlProperty(localName="HVS13") val HVS13:String, //중환자실 화상 기준 수
    @JacksonXmlProperty(localName="HVS14") val HVS14:String, //중환자실 외상 기준 수
    @JacksonXmlProperty(localName="HVS15") val HVS15:String, //중환자실 심장내과 기준 수
    @JacksonXmlProperty(localName="HVS16") val HVS16:String, //중환자실 흉부외과 기준 수
    @JacksonXmlProperty(localName="HVS17") val HVS17:String, //중환자실 일반 기준 수
    @JacksonXmlProperty(localName="HVS18") val HVS18:String, //중환자실  음압격리 기준 수
    @JacksonXmlProperty(localName="HVS19") val HVS19:String, //응급전용 입원실 기준 수
    @JacksonXmlProperty(localName="HVS20") val HVS20:String, //응급전용 소아입원실 기준 수
    @JacksonXmlProperty(localName="HVS21") val HVS21:String, //외상전용 입원실 기준 수
    @JacksonXmlProperty(localName="HVS22") val HVS22:String, //수술실 기준 수
    @JacksonXmlProperty(localName="HVS23") val HVS23:String, //외상전용 수술실 기준 수
    @JacksonXmlProperty(localName="HVS24") val HVS24:String, //정신과 폐쇄병동 입원실 기준 수
    @JacksonXmlProperty(localName="HVS25") val HVS25:String, //음압격리 기준 수
    @JacksonXmlProperty(localName="HVS26") val HVS26:String, //분만실 기준 수
    @JacksonXmlProperty(localName="HVS27") val HVS27:String, //CT 기준 수
    @JacksonXmlProperty(localName="HVS28") val HVS28:String, //MRI 기준 수
    @JacksonXmlProperty(localName="HVS29") val HVS29:String, //혈관 촬영기 기준 수
    @JacksonXmlProperty(localName="HVS30") val HVS30:String, //인공호흡기 일반 기준 수
    @JacksonXmlProperty(localName="HVS31") val HVS31:String, //인공호흡기 조산아 기준 수
    @JacksonXmlProperty(localName="HVS32") val HVS32:String, //인큐베이터 기준 수
    @JacksonXmlProperty(localName="HVS33") val HVS33:String, //CRRT 기준 수
    @JacksonXmlProperty(localName="HVS34") val HVS34:String, //ECMO기준 수
    @JacksonXmlProperty(localName="HVS35") val HVS35:String, //중심체온조절유도기 기준 수
    @JacksonXmlProperty(localName="HVS36") val HVS36:String, //화상전용처치실 기준 수
    @JacksonXmlProperty(localName="HVS37") val HVS37:String, //고압산소치료기 기준 수
    @JacksonXmlProperty(localName="HVS38") val HVS38:String, //일반 입원실 기준 수
    @JacksonXmlProperty(localName="HVS46") val HVS46:String, //격리진료구역 음압격리 기준 수
    @JacksonXmlProperty(localName="HVS47") val HVS47:String, //격리진료구역 일반격리 기준 수
    @JacksonXmlProperty(localName="HVS48") val HVS48:String, //소아음압격리 기준 수
    @JacksonXmlProperty(localName="HVS49") val HVS49:String, //소아일반격리 기준 수
    @JacksonXmlProperty(localName="HVS50") val HVS50:String, //응급전용 중환자실 음압격리 기준 수
    @JacksonXmlProperty(localName="HVS51") val HVS51:String, //응급전용 중환자시 일반격리 기준 수
    @JacksonXmlProperty(localName="HVS52") val HVS52:String, //응급전용 입원실 음압격리 기준 수
    @JacksonXmlProperty(localName="HVS53") val HVS53:String, //응급전용 입원실 일반격리 기준 수
    @JacksonXmlProperty(localName="HVS54") val HVS54:String, //감염병 전담병상 중환자실 기준 수
    @JacksonXmlProperty(localName="HVS55") val HVS55:String, //감염병 전담병상 중환자실 내 음압격리 병상 기준 수
    @JacksonXmlProperty(localName="HVS56") val HVS56:String, //감염 중증 병상 기준 수
    @JacksonXmlProperty(localName="HVS57") val HVS57:String, //감염 준-중증 병상 기준 수
    @JacksonXmlProperty(localName="HVS58") val HVS58:String, //감염 중등증 병상 기준 수
    @JacksonXmlProperty(localName="HVS59") val HVS59:String, //코호트 격리 기준 수
)
